name: API Test Framework
on:
  push: [ "main" ]
  pull_request: [ "main" ]
  schedule: [cron: "00 18 * * *"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    # CREATE logs folder FIRST
    - name: Setup logs directory
      run: mkdir -p logs
      
    - name: Execute test
      run: mvn clean test -Dsuite=testng -X
      
    # UPLOAD both Log4j + Surefire reports
    - name: Upload Logs & Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs-reports
        path: |
          logs/
          target/surefire-reports/
